// Proyectos
export const MOSTRAR_OCULTAR_FORMULARIO = 'MOSTRAR_OCULTAR_FORMULARIO';
export const OBTENER_PROYECTO = 'OBTENER_PROYECTO';
export const AGREGAR_PROYECTO = 'AGREGAR_PROYECTO';
export const PROYECTO_ACTUAL = 'PROYECTO_ACTUAL';
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';
// Tareas
export const OBTENER_TAREA = 'OBTENER_TAREA';
export const OBTENER_TAREA_PROYECTO = 'OBTENER_TAREA_PROYECTO';
export const AGREGAR_TAREA = 'AGREGAR_TAREA';
export const ELIMINAR_TAREA = 'ELIMINAR_TAREA';
export const PROYECTO_ERROR = 'PROYECTO_ERROR';
// al eliminar el proyecto elimina sus tareas del state
export const ELIMINAR_TAREAS_PROYECTO = 'ELIMINAR_TAREAS_PROYECTO';
export const ESTADO_TAREA = 'ESTADO_TAREA';
export const TAREA_ACTUAL = 'TAREA_ACTUAL';
export const ACTUALIZAR_TAREA = 'ACTUALIZAR_TAREA';
// authenticacion
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';
